language: node_js
node_js:
  - "8.11.2"

# S: Build Lifecycle
install:
  - npm install


script:
  - npm run build

after_script:
  - mv -f README.md dist
  - git clone "https://${GH_TOKEN}@${GH_REF}" demo
  - mv dist/* demo/
  - cd ./demo
  - git config user.name "stonehank"
  - git config user.email "stonehank310@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:main >/dev/null 2>&1
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH} >/dev/null 2>&1

# E: Build LifeCycle

branches:
  only:
    - main
env:
  global:
     - GH_REF: github.com/stonehank/diy-resume-demo
     - P_BRANCH: gh-pages
