import {v4 as uuidv4} from "uuid"

export default {
    "id": uuidv4(),
    "name": "sheet",
    "droppable": true,
    "children": [
        {
            "id": "637dfb76-71d1-44ff-ac6a-b1abe8389c35",
            "name": "paragraph",
            "styleConfig": {
                "margin": [0, 0, 0, 0],
                "padding": [0, 0, 0, 0],
                "borderTopWidth": 0,
                "borderRightWidth": 0,
                "borderBottomWidth": 0,
                "borderLeftWidth": 0,
                "borderColor": "#888",
                "borderTopLeftRadius": 4,
                "borderTopRightRadius": 4,
                "borderBottomRightRadius": 4,
                "borderBottomLeftRadius": 4,
                "borderStyle": "solid",
                "position": "static",
                "top": "auto",
                "left": "auto",
                "right": "auto",
                "bottom": "auto",
                "lineHeight": "24",
                "letterSpacing": "inherit",
                "textAlign": "inherit",
                "fontWeight": "inherit",
                "fontStyle": "inherit",
                "colorInherit": true,
                "fontSizeInherit": true,
                "backgroundInherit": true,
                "lineHeightInherit": false,
                "letterSpacingInherit": true,
                "textAlignInherit": true,
                "fontWeightInherit": true,
                "fontStyleInherit": true,
                "transform": null,
                "width": "100%",
                "height": "auto",
                "color": "inherit",
                "fontSize": "18",
                "background": "inherit",
                "col": 12
            },
            "config": {"icon": false, "appendIcon": null, "prependIcon": null, "value": "Some Unversity"},
            "pin": false,
            "slot": "school"
        }, {
            "id": "2b7ccb5c-6943-4be1-87af-8d8825ae9823",
            "name": "paragraph",
            "styleConfig": {
                "margin": [0, 0, 0, 0],
                "padding": [0, 0, 0, 0],
                "borderTopWidth": 0,
                "borderRightWidth": 0,
                "borderBottomWidth": 0,
                "borderLeftWidth": 0,
                "borderColor": "#888",
                "borderTopLeftRadius": 4,
                "borderTopRightRadius": 4,
                "borderBottomRightRadius": 4,
                "borderBottomLeftRadius": 4,
                "borderStyle": "solid",
                "position": "static",
                "top": "auto",
                "left": "auto",
                "right": "auto",
                "bottom": "auto",
                "lineHeight": "16",
                "letterSpacing": "inherit",
                "textAlign": "inherit",
                "fontWeight": "inherit",
                "fontStyle": "inherit",
                "colorInherit": false,
                "fontSizeInherit": false,
                "backgroundInherit": true,
                "lineHeightInherit": false,
                "letterSpacingInherit": true,
                "textAlignInherit": true,
                "fontWeightInherit": true,
                "fontStyleInherit": true,
                "transform": null,
                "width": "100%",
                "height": "auto",
                "color": "#5f5f5f",
                "fontSize": "14",
                "background": "inherit",
                "col": 12
            },
            "config": {"icon": false, "appendIcon": null, "prependIcon": null, "value": "Master "},
            "pin": false,
            "slot": "degree"
        }, {
            "id": "9c6d8adb-9a0b-40eb-b8ed-aba0182b33f4",
            "name": "paragraph",
            "styleConfig": {
                "margin": [0, 0, 0, "2"],
                "padding": [0, 0, 0, 0],
                "borderTopWidth": 0,
                "borderRightWidth": 0,
                "borderBottomWidth": 0,
                "borderLeftWidth": 0,
                "borderColor": "#888",
                "borderTopLeftRadius": 4,
                "borderTopRightRadius": 4,
                "borderBottomRightRadius": 4,
                "borderBottomLeftRadius": 4,
                "borderStyle": "solid",
                "position": "static",
                "top": "auto",
                "left": "auto",
                "right": "auto",
                "bottom": "auto",
                "lineHeight": "16",
                "letterSpacing": "inherit",
                "textAlign": "inherit",
                "fontWeight": "inherit",
                "fontStyle": "inherit",
                "colorInherit": false,
                "fontSizeInherit": false,
                "backgroundInherit": true,
                "lineHeightInherit": false,
                "letterSpacingInherit": true,
                "textAlignInherit": true,
                "fontWeightInherit": true,
                "fontStyleInherit": true,
                "transform": null,
                "width": "100%",
                "height": "auto",
                "color": "#848484",
                "fontSize": "13",
                "background": "inherit",
                "col": 12
            },
            "config": {"value": "2004-08-18 - 2010-08-26", "icon": false, "appendIcon": null, "prependIcon": null},
            "pin": false,
            "slot": "period"
        }, {
            "id": "4c9dd5df-96d7-4e49-9959-27b450168270",
            "name": "paragraph",
            "styleConfig": {
                "margin": [0, 0, 0, 0],
                "padding": [0, 0, 0, 0],
                "borderTopWidth": 0,
                "borderRightWidth": 0,
                "borderBottomWidth": 0,
                "borderLeftWidth": 0,
                "borderColor": "#888",
                "borderTopLeftRadius": 4,
                "borderTopRightRadius": 4,
                "borderBottomRightRadius": 4,
                "borderBottomLeftRadius": 4,
                "borderStyle": "solid",
                "position": "static",
                "top": "auto",
                "left": "auto",
                "right": "auto",
                "bottom": "auto",
                "lineHeight": "inherit",
                "letterSpacing": "inherit",
                "textAlign": "inherit",
                "color": "#242424",
                "fontSize": "13",
                "background": "inherit",
                "fontWeight": "inherit",
                "fontStyle": "inherit",
                "colorInherit": true,
                "fontSizeInherit": true,
                "backgroundInherit": true,
                "lineHeightInherit": true,
                "letterSpacingInherit": true,
                "textAlignInherit": true,
                "fontWeightInherit": true,
                "fontStyleInherit": true,
                "transform": null,
                "height": "auto",
                "col": 12
            },
            "config": {"value": "education description", "icon": false, "appendIcon": null, "prependIcon": null},
            "pin": false,
            "slot": "description"
        }],
    "styleConfig": {
        "margin": [0, 0, "16", 0],
        "padding": [0, 0, 0, 0],
        "borderTopWidth": 0,
        "borderRightWidth": 0,
        "borderBottomWidth": 0,
        "borderLeftWidth": 0,
        "borderColor": "#888",
        "borderTopLeftRadius": 4,
        "borderTopRightRadius": 4,
        "borderBottomRightRadius": 4,
        "borderBottomLeftRadius": 4,
        "borderStyle": "solid",
        "position": "static",
        "top": "auto",
        "left": "auto",
        "right": "auto",
        "bottom": "auto",
        "lineHeight": "16",
        "letterSpacing": "1",
        "textAlign": "inherit",
        "fontWeight": "400",
        "fontStyle": "normal",
        "colorInherit": true,
        "fontSizeInherit": false,
        "backgroundInherit": true,
        "lineHeightInherit": false,
        "letterSpacingInherit": false,
        "textAlignInherit": true,
        "fontWeightInherit": false,
        "fontStyleInherit": false,
        "transform": null,
        "width": "100%",
        "height": "auto",
        "color": "inherit",
        "fontSize": 16,
        "background": "inherit",
        "col": 12
    },
    "config": {},
    "pin": false,
    "slot": "educations",
    "index": 0
}
