import {v4 as uuidv4} from "uuid"

export default {
    "id": uuidv4(),
    "name": "sheet",
    "droppable": true,
    "children": [{
        "id": "91573116-1dec-437c-bec9-9b7569cc1e98",
        "name": "paragraph",
        "styleConfig": {
            "margin": [0, 0, 0, 0],
            "padding": [0, 0, 0, 0],
            "borderTopWidth": 0,
            "borderRightWidth": 0,
            "borderBottomWidth": 0,
            "borderLeftWidth": 0,
            "borderColor": "#888",
            "borderTopLeftRadius": 4,
            "borderTopRightRadius": 4,
            "borderBottomRightRadius": 4,
            "borderBottomLeftRadius": 4,
            "borderStyle": "solid",
            "position": "static",
            "top": "auto",
            "left": "auto",
            "right": "auto",
            "bottom": "auto",
            "lineHeight": "24",
            "letterSpacing": "inherit",
            "textAlign": "inherit",
            "fontWeight": "inherit",
            "fontStyle": "inherit",
            "colorInherit": true,
            "fontSizeInherit": true,
            "backgroundInherit": true,
            "lineHeightInherit": false,
            "letterSpacingInherit": true,
            "textAlignInherit": true,
            "fontWeightInherit": true,
            "fontStyleInherit": true,
            "transform": null,
            "width": "100%",
            "height": "auto",
            "color": "inherit",
            "fontSize": 18,
            "background": "inherit",
            "col": 12
        },
        "config": {"value": "project name", "icon": false, "appendIcon": null, "prependIcon": null},
        "pin": false,
        "slot": "name"
    }, {
        "id": "655de163-c1c1-4b8b-ac3b-93fddd440c67",
        "name": "anchor",
        "styleConfig": {
            "margin": [0, 0, 0, 0],
            "padding": [0, 0, 0, 0],
            "borderTopWidth": 0,
            "borderRightWidth": 0,
            "borderBottomWidth": 0,
            "borderLeftWidth": 0,
            "borderColor": "#888",
            "borderTopLeftRadius": 4,
            "borderTopRightRadius": 4,
            "borderBottomRightRadius": 4,
            "borderBottomLeftRadius": 4,
            "borderStyle": "solid",
            "position": "static",
            "top": "auto",
            "left": "auto",
            "right": "auto",
            "bottom": "auto",
            "lineHeight": "inherit",
            "letterSpacing": "inherit",
            "textAlign": "inherit",
            "fontWeight": "inherit",
            "fontStyle": "inherit",
            "colorInherit": false,
            "fontSizeInherit": false,
            "backgroundInherit": true,
            "lineHeightInherit": true,
            "letterSpacingInherit": true,
            "textAlignInherit": true,
            "fontWeightInherit": true,
            "fontStyleInherit": true,
            "transform": null,
            "width": "100%",
            "height": "auto",
            "color": "#2E87F9FF",
            "fontSize": "15",
            "background": "inherit",
            "col": 12
        },
        "config": {
            "value": "project link",
            "href": "www.EXAMPLE.com",
            "textDecoration": "underline",
            "icon": false,
            "appendIcon": null,
            "prependIcon": null
        },
        "pin": false,
        "slot": "link"
    }, {
        "id": "d4ce20f7-adfd-41dc-a871-45bc70616c2f",
        "name": "paragraph",
        "styleConfig": {
            "margin": [0, 0, 0, "2"],
            "padding": [0, 0, 0, 0],
            "borderTopWidth": 0,
            "borderRightWidth": 0,
            "borderBottomWidth": 0,
            "borderLeftWidth": 0,
            "borderColor": "#888",
            "borderTopLeftRadius": 4,
            "borderTopRightRadius": 4,
            "borderBottomRightRadius": 4,
            "borderBottomLeftRadius": 4,
            "borderStyle": "solid",
            "position": "static",
            "top": "auto",
            "left": "auto",
            "right": "auto",
            "bottom": "auto",
            "lineHeight": "16",
            "letterSpacing": "inherit",
            "textAlign": "inherit",
            "fontWeight": "inherit",
            "fontStyle": "inherit",
            "colorInherit": false,
            "fontSizeInherit": false,
            "backgroundInherit": true,
            "lineHeightInherit": false,
            "letterSpacingInherit": true,
            "textAlignInherit": true,
            "fontWeightInherit": true,
            "fontStyleInherit": true,
            "transform": null,
            "width": "100%",
            "height": "auto",
            "color": "#848484",
            "fontSize": "13",
            "background": "inherit",
            "col": 12
        },
        "config": {"value": "Start from 2020-04-22", "icon": false, "appendIcon": null, "prependIcon": null},
        "pin": false,
        "slot": "period"
    }, {
        "id": "83a3c25c-bd8c-491c-83a3-4fd2a1fa90dc",
        "name": "paragraph",
        "styleConfig": {
            "margin": [0, 0, 0, 0],
            "padding": [0, 0, 0, 0],
            "borderTopWidth": 0,
            "borderRightWidth": 0,
            "borderBottomWidth": 0,
            "borderLeftWidth": 0,
            "borderColor": "#888",
            "borderTopLeftRadius": 4,
            "borderTopRightRadius": 4,
            "borderBottomRightRadius": 4,
            "borderBottomLeftRadius": 4,
            "borderStyle": "solid",
            "position": "static",
            "top": "auto",
            "left": "auto",
            "right": "auto",
            "bottom": "auto",
            "lineHeight": "inherit",
            "letterSpacing": "inherit",
            "textAlign": "inherit",
            "fontWeight": "inherit",
            "fontStyle": "inherit",
            "colorInherit": true,
            "fontSizeInherit": false,
            "backgroundInherit": true,
            "lineHeightInherit": true,
            "letterSpacingInherit": true,
            "textAlignInherit": true,
            "fontWeightInherit": true,
            "fontStyleInherit": true,
            "transform": null,
            "width": "100%",
            "height": "auto",
            "color": "#242424",
            "fontSize": "13",
            "background": "inherit",
            "col": 12
        },
        "config": {"value": "project description", "icon": false, "appendIcon": null, "prependIcon": null},
        "pin": false,
        "slot": "description"
    }],
    "styleConfig": {
        "margin": [0, 0, "16", 0],
        "padding": [0, 0, 0, 0],
        "borderTopWidth": 0,
        "borderRightWidth": 0,
        "borderBottomWidth": 0,
        "borderLeftWidth": 0,
        "borderColor": "#888",
        "borderTopLeftRadius": 4,
        "borderTopRightRadius": 4,
        "borderBottomRightRadius": 4,
        "borderBottomLeftRadius": 4,
        "borderStyle": "solid",
        "position": "static",
        "top": "auto",
        "left": "auto",
        "right": "auto",
        "bottom": "auto",
        "lineHeight": "16",
        "letterSpacing": "1",
        "textAlign": "inherit",
        "fontWeight": "400",
        "fontStyle": "normal",
        "colorInherit": true,
        "fontSizeInherit": false,
        "backgroundInherit": true,
        "lineHeightInherit": false,
        "letterSpacingInherit": false,
        "textAlignInherit": true,
        "fontWeightInherit": false,
        "fontStyleInherit": false,
        "transform": null,
        "width": "100%",
        "height": "auto",
        "color": "inherit",
        "fontSize": 16,
        "background": "inherit",
        "col": 12
    },
    "config": {},
    "pin": false,
    "slot": "projects",
    "index": 0
}
